/*
 * Assemble the directory Cloudflare uploads: one exact Portal artifact plus host configuration.
 *
 * `dist` is an immutable, inventory-exact artifact. Portal's loader rejects a directory holding any
 * file its manifest does not name, so the next `portal:build` would refuse to replace an output
 * carrying one extra byte of ours. Cloudflare, meanwhile, reads `_redirects` and `_headers` only
 * from the root of the uploaded assets directory, and never serves them as assets. Those two facts
 * cannot both hold in one directory, so the deployed directory is assembled here instead: every
 * declared artifact file, copied under its manifest digest, plus the generated host configuration.
 *
 * Deployment configuration is generated from a rule table rather than hand-maintained in the
 * deployed tree, so the rules stay reviewable as data and the deployed file cannot drift from them.
 */

import { createHash, randomBytes } from "node:crypto";
import { lstat, mkdir, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

export const DEPLOYMENT_ASSEMBLY_RESULT_V1 =
  "https://getsuperbee.com/schemas/superbee-docs/deployment-assembly-result/v1";

const MANIFEST_PATH = "data/portal-manifest.json";

/** Cloudflare's own `_redirects` limits, restated so a generated file cannot silently exceed them. */
const MAX_STATIC_REDIRECT_RULES = 2000;
const MAX_LINE_LENGTH = 2000;
const PERMITTED_REDIRECT_STATUS = new Set([301, 302, 303, 307, 308]);

/**
 * Entry paths a reader guesses, redirected to the one canonical documentation root.
 *
 * Published pages live at `/docs/<id>/` and the documentation home is the site root, so bare
 * `/docs` and `/docs/` address nothing. Each rule names one exact path on purpose: a `/docs/*`
 * rule would match every missing page under the prefix and turn a genuine 404 into a silent
 * redirect, which is the opposite of telling a reader that the page they asked for is gone.
 */
export const DEPLOYMENT_REDIRECTS = Object.freeze([
  Object.freeze({ from: "/docs", to: "/", status: 301 }),
  Object.freeze({ from: "/docs/", to: "/", status: 301 }),
]);

const sha256 = (bytes) => `sha256:${createHash("sha256").update(bytes).digest("hex")}`;

function assertExactRoute(value, field) {
  if (typeof value !== "string" || !value.startsWith("/") || /\s/u.test(value)) {
    throw new Error(`redirect ${field} must be one absolute whitespace-free path; got ${JSON.stringify(value)}`);
  }
  // A wildcard or a `:name` placeholder would widen a rule past the exact route it declares.
  if (value.includes("*") || /:[A-Za-z]/u.test(value)) {
    throw new Error(`redirect ${field} '${value}' must not use a wildcard or a placeholder`);
  }
}

/** Render the exact `_redirects` bytes Cloudflare parses, refusing any rule it would discard. */
export function renderRedirects(rules = DEPLOYMENT_REDIRECTS) {
  if (rules.length > MAX_STATIC_REDIRECT_RULES) {
    throw new Error(`at most ${MAX_STATIC_REDIRECT_RULES} static redirect rules are supported`);
  }
  const seen = new Set();
  const lines = [
    "# Generated by scripts/deployment-assets.mjs from DEPLOYMENT_REDIRECTS.",
    "# Edit that rule table, never a deployed copy of this file.",
  ];
  for (const rule of rules) {
    assertExactRoute(rule.from, "source");
    assertExactRoute(rule.to, "target");
    if (!PERMITTED_REDIRECT_STATUS.has(rule.status)) {
      throw new Error(`redirect status ${rule.status} is not one Cloudflare accepts`);
    }
    if (seen.has(rule.from)) throw new Error(`duplicate redirect source '${rule.from}'`);
    seen.add(rule.from);
    /*
     * Cloudflare discards a rule whose source ends in `/` and whose target ends in `/index` or
     * `/index.html`, because `html_handling` would rewrite the target straight back into the rule.
     * Refuse here so a discarded rule can never reach production as a silent 404.
     */
    if (rule.from.endsWith("/") && /\/index(?:\.html)?$/u.test(rule.to)) {
      throw new Error(`redirect '${rule.from}' -> '${rule.to}' would loop through html handling`);
    }
    const line = `${rule.from} ${rule.to} ${rule.status}`;
    if (line.length > MAX_LINE_LENGTH) throw new Error(`redirect line exceeds ${MAX_LINE_LENGTH} characters`);
    lines.push(line);
  }
  return `${lines.join("\n")}\n`;
}

/** The host configuration files Cloudflare consumes from the uploaded assets directory root. */
export function deploymentConfigurationFiles() {
  return new Map([["_redirects", renderRedirects()]]);
}

async function inventory(root, prefix = "") {
  const rows = [];
  const directory = prefix ? path.join(root, ...prefix.split("/")) : root;
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    const info = await lstat(path.join(directory, entry.name));
    if (info.isSymbolicLink() || (!info.isFile() && !info.isDirectory())) {
      throw new Error(`the portal artifact may contain only regular files and directories; found ${relative}`);
    }
    if (info.isDirectory()) rows.push(...await inventory(root, relative));
    else rows.push(relative);
  }
  return rows.sort();
}

/**
 * A previous assembly always carries the artifact manifest at its exact path. Anything else in the
 * deployment directory is a tree this script did not create, and is not ours to replace.
 */
async function replaceableOutput(directory) {
  let entries;
  try {
    const info = await lstat(directory);
    if (info.isSymbolicLink() || !info.isDirectory()) {
      throw new Error(`refusing to replace '${directory}': it is not a regular directory`);
    }
    entries = await readdir(directory);
  } catch (error) {
    if (error.code === "ENOENT") return false;
    throw error;
  }
  if (entries.length === 0) return true;
  try {
    await lstat(path.join(directory, ...MANIFEST_PATH.split("/")));
  } catch {
    throw new Error(`refusing to replace '${directory}': it is not a previous deployment assembly`);
  }
  return true;
}

/**
 * Copy the exact declared artifact inventory into the deployment directory and add the host
 * configuration. Every file is verified against the manifest digest it was published under, so an
 * assembled deployment can only carry bytes this repository built.
 */
export async function assembleDeployment({ artifact = "dist", output = "deploy" } = {}) {
  const artifactRoot = path.resolve(artifact);
  const outputRoot = path.resolve(output);
  if (artifactRoot === outputRoot
    || outputRoot.startsWith(`${artifactRoot}${path.sep}`)
    || artifactRoot.startsWith(`${outputRoot}${path.sep}`)) {
    throw new Error("the portal artifact and the deployment directory must not overlap");
  }
  const manifestBytes = await readFile(path.join(artifactRoot, ...MANIFEST_PATH.split("/")));
  const manifest = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(manifestBytes));
  if (!Array.isArray(manifest.files) || manifest.files.length === 0) {
    throw new Error("the portal manifest must declare its file inventory");
  }
  const declared = [...manifest.files].sort((left, right) => (left.path < right.path ? -1 : left.path > right.path ? 1 : 0));
  const expected = [...declared.map((file) => file.path), MANIFEST_PATH].sort();
  const observed = await inventory(artifactRoot);
  if (JSON.stringify(observed) !== JSON.stringify(expected)) {
    throw new Error(`'${artifactRoot}' does not exactly match its declared portal inventory; rebuild it`);
  }
  const configuration = deploymentConfigurationFiles();
  for (const name of configuration.keys()) {
    if (expected.includes(name)) throw new Error(`deployment configuration '${name}' collides with a published asset`);
  }

  const parent = path.dirname(outputRoot);
  const nonce = randomBytes(8).toString("hex");
  const stage = path.join(parent, `.superbee-deployment-stage-${nonce}`);
  const backup = path.join(parent, `.superbee-deployment-backup-${nonce}`);
  await mkdir(parent, { recursive: true });
  await mkdir(stage, { mode: 0o700 });
  let bytes = 0;
  let moved = false;
  let installed = false;
  try {
    for (const file of [...declared, { path: MANIFEST_PATH }]) {
      const source = await readFile(path.join(artifactRoot, ...file.path.split("/")));
      if (file.digest !== undefined && sha256(source) !== file.digest) {
        throw new Error(`published file '${file.path}' does not match its manifest digest`);
      }
      const destination = path.join(stage, ...file.path.split("/"));
      await mkdir(path.dirname(destination), { recursive: true, mode: 0o700 });
      await writeFile(destination, source, { mode: 0o600, flag: "wx" });
      bytes += source.byteLength;
    }
    for (const [name, content] of configuration) {
      const encoded = Buffer.from(content, "utf8");
      await writeFile(path.join(stage, name), encoded, { mode: 0o600, flag: "wx" });
      bytes += encoded.byteLength;
    }
    const replacing = await replaceableOutput(outputRoot);
    if (replacing) {
      await rename(outputRoot, backup);
      moved = true;
    }
    await rename(stage, outputRoot);
    installed = true;
    if (moved) {
      await rm(backup, { recursive: true, force: true });
      moved = false;
    }
  } catch (error) {
    if (moved && !installed) await rename(backup, outputRoot).catch(() => undefined);
    await rm(stage, { recursive: true, force: true });
    throw error;
  }
  return {
    schema: DEPLOYMENT_ASSEMBLY_RESULT_V1,
    ok: true,
    artifact: artifactRoot,
    output: outputRoot,
    artifactDigest: manifest.artifactDigest,
    files: declared.length + 1,
    configuration: [...configuration.keys()],
    bytes,
  };
}

async function main(argv) {
  const options = { artifact: "dist", output: "deploy" };
  for (let index = 0; index < argv.length; index += 2) {
    const flag = argv[index];
    const value = argv[index + 1];
    if (flag === "--artifact" && value) options.artifact = value;
    else if (flag === "--output" && value) options.output = value;
    else throw new Error("usage: node scripts/deployment-assets.mjs [--artifact <directory>] [--output <directory>]");
  }
  console.log(JSON.stringify(await assembleDeployment(options)));
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  await main(process.argv.slice(2));
}
